### ISSUE TITLE
when typed the city id this error is being shown

### ISSUE THREAD

**Issue by stijojoseph** [sharadbhat/Zomatopy#7]
Traceback (most recent call last):

  File "<ipython-input-27-ae7654fb082f>", line 12, in <module>
    a = ast.literal_eval(r)

  File "C:\Users\HP\Anaconda3\lib\ast.py", line 91, in literal_eval
    return _convert(node_or_string)

  File "C:\Users\HP\Anaconda3\lib\ast.py", line 79, in _convert
    map(_convert, node.values)))

  File "C:\Users\HP\Anaconda3\lib\ast.py", line 90, in _convert
    return _convert_signed_num(node)

  File "C:\Users\HP\Anaconda3\lib\ast.py", line 63, in _convert_signed_num
    return _convert_num(node)

  File "C:\Users\HP\Anaconda3\lib\ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))

ValueError: malformed node or string: <_ast.Name object at 0x000002321E54E2C8>

**Comment by Abhiram4572** [comment]
This is due, to some inconsistent space characters (like \n, etc) in the response received, Use something like below to handle them. I hope it helps.
    
    import re
    import json

    #search_url and params are the same as mentioned in the original code.

    response = (requests.get(search_url,headers = params))
    response = re.sub('\s+', ' ', response.text)
    data = json.loads(response)
